files: '.py|.json'
exclude: '.git'
default_stages: [commit]

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-json
        files: '.json'

  - repo: https://github.com/AgnieszkaZaba/devops_tests
    rev: b2f0a463b946d4d229e2e5edf2bed0c0f4c566d0
    hooks:
      - id: check-notebook-open-atmos-structure
        name: check notebook has open-atmos structure
        args: [--repo-name=PyMPDATA]
