name: pypi

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'
  release:
    types: [published]

jobs:
  dist:
    strategy:
      matrix:
        package-dir: [".", "examples", "MPI"]
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0  # https://github.com/pypa/setuptools_scm/issues/480
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - run: pip install twine build

      - run: |
          unset CI
          cd ${{ matrix.package-dir }}
          python -m build 2>&1 | tee build.log
          exit `fgrep -v "warning: no previously-included files matching" buid.log | fgrep -i warning | wc -l`
          twine check --strict dist/*
          exit `tar tzf dist/*.tar.gz | fgrep ".ipynb" | wc -l`
          cd ..

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          attestations: false
          repository_url: https://test.pypi.org/legacy/
          packages-dir: ${{ matrix.package-dir }}/dist

      - if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          attestations: false
          packages-dir: ${{ matrix.package-dir }}/dist
